### ISSUE TITLE
wrapper does not find cdo in conda env

### ISSUE THREAD

**Issue by cehbrecht** [Try2Code/cdo-bindings#17]
Since version 1.3.4 it looks like the initialization of the cdo wrapper has changed. I'm installing both cdo and python-cdo via conda. But the cdo wrapper can not find the cdo tool in the `PATH`. I need to set the `PATH` when I initialize the cdo wrapper:

```
import os
from cdo import Cdo
cdo = Cdo(env=os.environ)
```

**Comment by Try2Code** [comment]
Hi Carsten! sorry, totally missed this ticket. I will try to reproduce this with conda. Do you use python2 or python3?

**Comment by cehbrecht** [comment]
@Try2Code 
I'm using cdo in a python2 environment ... haven't checked on python3.

**Comment by Try2Code** [comment]
hi!

I did a cross-check on m,y linux box but could not reproduce the error. Leaving out `env=os.environ` just  works. 

... will give you a call

**Comment by cehbrecht** [comment]
@Try2Code 
right ... it is working now. I have tried my conda environment and I have on complains. Tested on Python 2.7, Debian and CentOS 7. 

I close this ticket.

**Comment by Try2Code** [comment]
Hi carsten!
Other people seem to gave similar issues with this (https://code.mpimet.mpg.de/issues/7985). so I took over your suggestion ```env=os.environ``` as the ne default.
It will be availabe in the next release 1.3.6
