### ISSUE TITLE
Error loading netCDF4 after installing CDO

### ISSUE THREAD

**Issue by kristydahl** [Try2Code/cdo-bindings#20]
I have successfully installed CDO and have confirmed that it is working from the command line. But I'm having trouble getting the python bindings to work. The problem seems to be with the netCDF4 module, which is installed in the same directory as cdo. 

Here is the error I get when I try to import the netCDF4 module in python:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(netCDF4/_netCDF4.so, 2): Symbol not found: _clock_gettime
  Referenced from: netCDF4/.dylibs/libcurl.4.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in netCDF4/.dylibs/libcurl.4.dylib`

And when I try to initialize cdo: 
`>>> cdo = Cdo()
Could not load netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cdo.py", line 135, in __init__
    self.loadCdf()  # load netcdf lib if possible and set self.cdf }}}
  File "cdo.py", line 431, in loadCdf
    from netCDF4 import Dataset as cdf
  File "netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(netCDF4/_netCDF4.so, 2): Symbol not found: _clock_gettime
  Referenced from: netCDF4/.dylibs/libcurl.4.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in netCDF4/.dylibs/libcurl.4.dylib
`

Any suggestions for how to fix?

**Comment by Try2Code** [comment]
please use 'pip' for installation of netCDF4 (and possibly cdo.py). this should solve these kind of problems.

**Comment by kristydahl** [comment]
Thanks for your suggestion. I used pip to install netCDF4 and the cdo bindings (pip install netCDF4 and pip install cdo) prior to getting these errors.

**Comment by Try2Code** [comment]
ah, ok, sorry - you mentioned that both modules are installed in the same directory and that's usually not the case with pip AFAIK. 
i would run some simple tests with netcdf4, only. a manual installation of netcdf4 might help, too

**Comment by Try2Code** [comment]
did a X-check on a MacOS-system i have access to, but wasn't able to re-produce this error. I used
cdo-1.9.5
cdo.py-1.4.0

```python
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdo
>>> c = cdo.Cdo()
>>> t =  c.topo(returnArray='topo')
>>> print(t)
[[ 2783.3333  2783.3333  2783.3333 ...  2783.3333  2783.3333  2783.3333]
 [ 2939.      2937.      2934.3333 ...  2946.      2944.      2941.3333]
 [ 3068.3333  3066.3333  3064.3333 ...  3074.      3072.      3070.3333]
 ...
 [-1531.     -1552.3334 -1589.     ... -1436.6666 -1467.6666 -1502.3334]
 [-3007.     -2986.3333 -2986.3333 ... -3263.     -3154.     -3060.6667]
 [-4117.6665 -4114.6665 -4112.     ... -4134.3335 -4127.6665 -4122.    ]]
```

**Comment by Try2Code** [comment]
is this solved now?

**Comment by kristydahl** [comment]
I never did get the cdo bindings working, so ended up just using
workarounds like using subprocess commands. I also ended up using nco tools
more than cdo, so found less of a need for the cdo bindings. Thanks!

**Comment by Try2Code** [comment]
allright, then I close this ticket

please feel free to approach me in case you need further help
