### ISSUE TITLE
Support converting .dat file to .nc file

### ISSUE THREAD

**Issue by zxdawn** [Try2Code/cdo-bindings#21]
It's convenient to convert *dat* file to *nc* file in command line:
```
cdo -f nc import_binary ${ctl_file} ${ncname}
```
How to deal with it in python?

**Comment by zxdawn** [comment]
I'm using `os.system()` to run the command. Maybe, there's a better solution.

**Comment by Try2Code** [comment]
hey! sorry for being late. the call looks like
```python
from cdo import Cdo

cdo = Cdo()

cdo.import_binary(input=ctl_file,output='output.nc')
```

**Comment by zxdawn** [comment]
@Try2Code Thanks, I'll test it after holiday~

**Comment by Try2Code** [comment]
the github notification must have got lost in my mail folder during holiday :woman_shrugging:

**Comment by Try2Code** [comment]
btw: have a nice holiday  - and don't read mail ;-)

**Comment by Try2Code** [comment]
any update @zxdawn ??

**Comment by zxdawn** [comment]
@Try2Code I remember that it works well :) Sorry for the late update.

**Comment by viictor-m** [comment]
hey! sorry to bring this up again. 
i'm trying to this (windows based) and it doesnt work.
the error message is "[WinError 2] System could not find the specified archive". Could you help me, please?
