### ISSUE TITLE
Segmentation fault when using bindings

### ISSUE THREAD

**Issue by JanVog** [Try2Code/cdo-bindings#24]
When using the python bindings for cdo I get a segmentation fault that I don't get when running the same command on the command line.
In python I have the following chained command:
```python
cdo.setreftime("1970-01-01,00:00:00", input="-sellonlatbox,{lon0},{lon1},-90,90 -settunits,hours -setcalendar,standard -masklonlatbox,0,360,-90,90 -remapnn,custom_grid.txt {input}".format(lon0=center-180, lon1=center+180.1, input=path_to_input), output=path_to_output, options = "-P 8 -f nc4 -z zip")
```
When running this script I get the following output:
```bash
>>> cdo -O -P 8 -f nc4 -z zip -setreftime,1970-01-01,00:00:00 -sellonlatbox,-180.0,180.1,-90,90 -settunits,hours -setcalendar,standard -masklonlatbox,0,360,-90,90 -remapnn,custom_grid.txt data/gfas_frpfire_Aug2019.nc data/gfas_frpfire_Aug2019_processed.nc<<<
[...]
Segmentation fault (core dumped)
```

When I now run the command that the python bindings probably executed (`cdo -O ...`) on the command line (without python) I do not get a Segmentation fault. The python program does nothing else, so the error really comes from running the command above.

Any idea why this is happening? I am not sure if I built all libraries (hdf, netcdf4) threadsafe but this should not be the problem as there is no SegFault when running the command on the command line.

**Comment by Try2Code** [comment]
hi @JanVog 
sorry for the late reply - I don't get any notifications unless  I am mentioned in the text. 

could you upload the data or parts of it? it's will be easier to reproduce the behaviour then. you can also use the forum at https://code.mpimet.mpg.de/projects/cdo/boards instead. there you can upload things directly. And I get notoified when someone writes a message there.

cheers
