### ISSUE TITLE
Feature request: PyCDO for/from Bash

### ISSUE THREAD

**Issue by pgierz** [Try2Code/cdo-bindings#29]
Hello,

I have a bit of a "bizarre" feature request. It is sometimes nice to use pycdo on your own to build nice command chains. However, I often have colleagues who are not so good at python. It might therefore be nice to have an option to spit out whatever the current command chain would look like to a shell script. Sine pycdo calls subprocesses anyway in the background, it should be something as simple as grabbing whatever you are about to send to the shell, and printing it to a file instead.

Might also be nice for debugging.

On the other side (yet this is much more tricky from a gut feeling) it might be nice to sometimes be able to take some sort of shell script, read it in, and generate an equivalent CDO 'object' to keep using afterward. Tricks here might involve recognizing multiple cdo commands, since given *any* user input, there will likely be more than just one command in there.

What do you think?

Cheers
Paul

**Comment by larsbuntemeyer** [comment]
Hi  @pgierz ,
i often use the logging option together with the logfile option, e.g.
```python
cdo = Cdo(logging=True, logFile='cdo_commands.log')
```
if that's what you mean by the "bizzarre" request!

cheers
lars

**Comment by Try2Code** [comment]
thx @larsbuntemeyer  - good to hear that someone else us using it ;-)

**Comment by pgierz** [comment]
Closing this. @larsbuntemeyer thanks very much for the hint :-) I guess the idea of flipping it to "read shell and create python CDO object" will almost never be needed in practice, and is too much of an engineering. We should probably all be writing papers anyway...
