### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by pgierz** [Try2Code/cdo-bindings#30]
Hello,

I noticed that the version on PyPI is not up to date with the GitHub version. Can we update this please?

Thanks!
Paul

**Comment by Try2Code** [comment]
hi @pgierz 
pip hast version 1.5.3 - whats missing? 

the development version is not ready because I still want to change things.

**Comment by pgierz** [comment]
In particular this bit: https://github.com/Try2Code/cdo-bindings/blob/a4e9a8a1dc63ca9e2ac89ae8312c76d0af54dd48/python/cdo.py#L146

One of our supercomputers has the annoying habit of setting the env variable `CDO=True` (don't ask me why), so I need to patch in [this change here](https://github.com/Try2Code/cdo-bindings/commit/26cfaa1a6c1a67b772e47275508f1fcc801e9218) to all of my students installations.

I know it's only one little line, but would it be a big effort to make `1.5.4` with that change?

**Comment by pgierz** [comment]
This is actually causing me some problems in downstream tools, since I now can't upload a working version to PyPI:
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
122
Invalid value for requires_dist. Error: Can't have direct dependency: 'cdo @ git+https://github.com/Try2Code/cdo-bindings#egg=pkg&subdirectory=python'
```

**Comment by Try2Code** [comment]
1.5.4 has just been released with your changeset @pgierz

**Comment by pgierz** [comment]
Thanks!! My downstream stuff works now 😄
