### ISSUE TITLE
Mention how the bindings are supported in python-cdo package from conda-forge

### ISSUE THREAD

**Issue by jypeter** [Try2Code/cdo-bindings#33]
I had to search the [cdo web site](https://code.mpimet.mpg.de/projects/cdo/wiki/Cdo#Documentation) and forum to understand that the python bindings can now be installed with `conda install -c conda-forge python-cdo`, and that the conda-forge `cdo` package is only for providing the executable

Could this **very useful information** be added to the [cdo-bindings ](https://github.com/Try2Code/cdo-bindings) and the [Using CDO from python or ruby](https://code.mpimet.mpg.de/projects/cdo/wiki/Cdo%7Brbpy%7D#Python) pages?

Thanks!

**Comment by Try2Code** [comment]
I updated the second link.The documentation about the conda package for the CDO binary includes the respective hint to the python bindings: https://code.mpimet.mpg.de/projects/cdo/wiki/Anaconda

thx for the hint

**Comment by jypeter** [comment]
Thanks!
