### ISSUE TITLE
threaded cdo

### ISSUE THREAD

**Issue by larsbuntemeyer** [Try2Code/cdo-bindings#34]
hi @Try2Code ,
thanks again for this, i like to use cdo through these bindings. i have an issue that just recently came up when i try to use `dask.distributed` to use the rather heavy `sp2gpl` operator on ERA5 data. I like to delay the execution and run then on several timesteps in parallel. i'll try to make a reproducible case here, e.g.,

setup dask client
```python
from dask.distributed import Client, progress
client = Client()
client
``` 
![Screenshot 2021-07-19 at 23 12 32](https://user-images.githubusercontent.com/5659125/126228120-ef85cbcb-5511-4d86-81ba-23dabc3ff9ab.png)

test dataset
```python
import xarray as xr
ds = xr.tutorial.open_dataset("air_temperature")
ds.sel(time='2013-01-01')
```

some operator that could be embarassingly parallel:
```python
from cdo import Cdo

def test_op(input):
    return Cdo().setgridtype('curvilinear', options='-f nc4', input=input)
```
lazy evaluation with dask: write out each timestep into a single file and run the operator on that.
```python
def apply(ds, use_dask=False):
    if use_dask:
        from dask import delayed
    else:
        def delayed(x):
            return x
    output = []
    for ti in ds.time:
        # expand_dims so that cdo's to_netcdf call keeps time coordinate in nc file.
        ti_res = delayed(test_op)(ds.sel(time = ti).expand_dims(dim='time'))
        output.append(ti_res)
    return output
```
Now apply our operator onto the dataset (just the first 10 timesteps for testing...)
```python
out = apply(ds.isel(time=range(0,10)), use_dask=True)
out
```
![Screenshot 2021-07-19 at 23 18 19](https://user-images.githubusercontent.com/5659125/126229085-f1f8f6c6-b3b6-4650-91cc-ec04e0ca96c7.png)

This all works fine, however, when i actually trigger the computation, i get this signal error:
```python
import dask
%time out_ = dask.compute(out)
```
![Screenshot 2021-07-19 at 23 22 42](https://user-images.githubusercontent.com/5659125/126229287-af50610b-3441-4a2b-9024-797320f2761b.png)

### proposed solution

The problem seems to be with signal handling in threads. I could actually avoid the error if the signal handling only runs in the main thread, e.g., something like this in `cdo.py`

```python
 if threading.current_thread() is threading.main_thread():
        signal.signal(signal.SIGINT, self.__catch__)
        signal.signal(signal.SIGTERM, self.__catch__)
        signal.signal(signal.SIGSEGV, self.__catch__)
        signal.siginterrupt(signal.SIGINT, False)
        signal.siginterrupt(signal.SIGTERM, False)
        signal.siginterrupt(signal.SIGSEGV, False)
```

I runs fine then and actually scales quite nicely, but i am not sure about correctly handling signals in threads. my solution might be naive. It would really be nice to be able to delay cdo computations with dask to integrate them with other workflows... hope, i could make myself clear :) thanks!!!

**Comment by Try2Code** [comment]
hi @larsbuntemeyer 
so you already patched `cdo.py` in your environment, right?

**Comment by Try2Code** [comment]
your suggestions looks good, but I need some time for testing first. ... not too fluent in dask

**Comment by larsbuntemeyer** [comment]
yes, thanks, i have a patch. i can help with making up a test create a draft request.

**Comment by Try2Code** [comment]
I could reproduce the error now. Need a bit to consolidate the different development branches.  but the PR is the right way to go

thx for setting it up :+1:

**Comment by larsbuntemeyer** [comment]
thanks!

**Comment by Try2Code** [comment]
i will put it on conda-forge, too
