### ISSUE TITLE
Hi sir,I am trying to install python-cdo by using "conda create -n cdo_test python=3 cdo python-cdo" and it shows error.

### ISSUE THREAD

**Issue by sujathasujji** [Try2Code/cdo-bindings#41]
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python-cdo
  - cdo==1.9.9

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Note: you may need to restart the kernel to use updated packages.

**Comment by Try2Code** [comment]
hi!

you need to use the `conda-forge` channel for getting `cdo` and `python-cdo`

cheers
ralf
