### ISSUE TITLE
Hard coded `-s`

### ISSUE THREAD

**Issue by wachsylon** [Try2Code/cdo-bindings#45]
Moin Brian @Try2Code,

it seems like I have no option to access the stdout of operators which makes it hard to use `verifygrid` or `cmor`.
Could we implement sth to enable that? Maybe a logfile or sth?

Best,
Fabi

**Comment by Try2Code** [comment]
hi! I add a new options called `silent` plus some tests regarding the verifygrid output in the `maintenance-1.5.x` branch.

Please have look at this: https://github.com/Try2Code/cdo-bindings/blob/maintenance-1.5.x/python/test/test_cdo.py#L794

setting `cdo.silent = False` should me the desired output available to the calling application. Please give it a try. I can create a new minor release for that in no time

**Comment by Try2Code** [comment]
This feature is now part of the 1.5.7 release
